
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'CardAssetCard': typeof import("../components/Card/AssetCard.vue")['default']
    'HeaderCustomMenu': typeof import("../components/Header/CustomMenu.vue")['default']
    'HeaderMenu': typeof import("../components/Header/Menu.vue")['default']
    'ModalCreateProduct': typeof import("../components/Modal/createProduct.vue")['default']
    'ModalProductModal': typeof import("../components/Modal/productModal.vue")['default']
    'ProductAddQuantity': typeof import("../components/Product/AddQuantity.vue")['default']
    'SidebarCustomMenu': typeof import("../components/Sidebar/CustomMenu.vue")['default']
    'SidebarMenu': typeof import("../components/Sidebar/Menu.vue")['default']
    'TableAssetActiveTable': typeof import("../components/Table/Asset/ActiveTable.vue")['default']
    'TableAssetBrokenTable': typeof import("../components/Table/Asset/BrokenTable.vue")['default']
    'TableAssetInactiveTable': typeof import("../components/Table/Asset/InactiveTable.vue")['default']
    'TableAssetOver250': typeof import("../components/Table/Asset/over250.vue")['default']
    'TableAssetUnder250': typeof import("../components/Table/Asset/under250.vue")['default']
    'TableRepair': typeof import("../components/Table/Repair/Repair.vue")['default']
    'TableTaskMonthlyTable': typeof import("../components/Table/Task/MonthlyTable.vue")['default']
    'TableTaskTodayTable': typeof import("../components/Table/Task/TodayTable.vue")['default']
    'TableTaskWeeklyTable': typeof import("../components/Table/Task/WeeklyTable.vue")['default']
    'UtilsValueUpdater': typeof import("../components/utils/valueUpdater.vue")['default']
    'UAccordion': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Accordion.vue")['default']
    'UAlert': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Alert.vue")['default']
    'UAvatar': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Avatar.vue")['default']
    'UAvatarGroup': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/AvatarGroup")['default']
    'UBadge': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Badge.vue")['default']
    'UButton': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Button.vue")['default']
    'UButtonGroup': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/ButtonGroup")['default']
    'UCarousel': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Carousel.vue")['default']
    'UChip': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Chip.vue")['default']
    'UDropdown': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Dropdown.vue")['default']
    'UIcon': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Icon.vue")['default']
    'UKbd': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Kbd.vue")['default']
    'ULink': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Link.vue")['default']
    'UMeter': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Meter.vue")['default']
    'UMeterGroup': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/MeterGroup")['default']
    'UProgress': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Progress.vue")['default']
    'UCheckbox': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Checkbox.vue")['default']
    'UForm': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Form.vue")['default']
    'UFormGroup': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/FormGroup.vue")['default']
    'UInput': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Input.vue")['default']
    'UInputMenu': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/InputMenu.vue")['default']
    'URadio': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Radio.vue")['default']
    'URadioGroup': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/RadioGroup.vue")['default']
    'URange': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Range.vue")['default']
    'USelect': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Select.vue")['default']
    'USelectMenu': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/SelectMenu.vue")['default']
    'UTextarea': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Textarea.vue")['default']
    'UToggle': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Toggle.vue")['default']
    'UTable': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/data/Table.vue")['default']
    'UCard': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Card.vue")['default']
    'UContainer': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Container.vue")['default']
    'UDivider': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Divider.vue")['default']
    'USkeleton': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Skeleton.vue")['default']
    'UBreadcrumb': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/Breadcrumb.vue")['default']
    'UCommandPalette': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/CommandPalette.vue")['default']
    'UCommandPaletteGroup': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/CommandPaletteGroup.vue")['default']
    'UHorizontalNavigation': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/HorizontalNavigation.vue")['default']
    'UPagination': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/Pagination.vue")['default']
    'UTabs': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/Tabs.vue")['default']
    'UVerticalNavigation': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/VerticalNavigation.vue")['default']
    'UContextMenu': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/ContextMenu.vue")['default']
    'UModal': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Modal.vue")['default']
    'UModals': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Modals.client.vue")['default']
    'UNotification': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Notification.vue")['default']
    'UNotifications': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Notifications.vue")['default']
    'UPopover': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Popover.vue")['default']
    'USlideover': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Slideover.vue")['default']
    'USlideovers': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Slideovers.client.vue")['default']
    'UTooltip': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Tooltip.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'Icon': typeof import("../node_modules/@nuxt/icon/dist/runtime/components/index")['default']
    'ColorScheme': typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
    'Accordion': typeof import("../components/ui/accordion/index")['Accordion']
    'AccordionContent': typeof import("../components/ui/accordion/index")['AccordionContent']
    'AccordionItem': typeof import("../components/ui/accordion/index")['AccordionItem']
    'AccordionTrigger': typeof import("../components/ui/accordion/index")['AccordionTrigger']
    'Badge': typeof import("../components/ui/badge/index")['Badge']
    'Breadcrumb': typeof import("../components/ui/breadcrumb/index")['Breadcrumb']
    'BreadcrumbEllipsis': typeof import("../components/ui/breadcrumb/index")['BreadcrumbEllipsis']
    'BreadcrumbItem': typeof import("../components/ui/breadcrumb/index")['BreadcrumbItem']
    'BreadcrumbLink': typeof import("../components/ui/breadcrumb/index")['BreadcrumbLink']
    'BreadcrumbList': typeof import("../components/ui/breadcrumb/index")['BreadcrumbList']
    'BreadcrumbPage': typeof import("../components/ui/breadcrumb/index")['BreadcrumbPage']
    'BreadcrumbSeparator': typeof import("../components/ui/breadcrumb/index")['BreadcrumbSeparator']
    'Button': typeof import("../components/ui/button/index")['Button']
    'Card': typeof import("../components/ui/card/index")['Card']
    'CardHeader': typeof import("../components/ui/card/index")['CardHeader']
    'CardTitle': typeof import("../components/ui/card/index")['CardTitle']
    'CardDescription': typeof import("../components/ui/card/index")['CardDescription']
    'CardContent': typeof import("../components/ui/card/index")['CardContent']
    'CardFooter': typeof import("../components/ui/card/index")['CardFooter']
    'ChartTooltip': typeof import("../components/ui/chart/index")['ChartTooltip']
    'ChartSingleTooltip': typeof import("../components/ui/chart/index")['ChartSingleTooltip']
    'ChartLegend': typeof import("../components/ui/chart/index")['ChartLegend']
    'ChartCrosshair': typeof import("../components/ui/chart/index")['ChartCrosshair']
    'BarChart': typeof import("../components/ui/chart-bar/index")['BarChart']
    'DonutChart': typeof import("../components/ui/chart-donut/index")['DonutChart']
    'Checkbox': typeof import("../components/ui/checkbox/index")['Checkbox']
    'Collapsible': typeof import("../components/ui/collapsible/index")['Collapsible']
    'CollapsibleContent': typeof import("../components/ui/collapsible/index")['CollapsibleContent']
    'CollapsibleTrigger': typeof import("../components/ui/collapsible/index")['CollapsibleTrigger']
    'Dialog': typeof import("../components/ui/dialog/index")['Dialog']
    'DialogClose': typeof import("../components/ui/dialog/index")['DialogClose']
    'DialogTrigger': typeof import("../components/ui/dialog/index")['DialogTrigger']
    'DialogHeader': typeof import("../components/ui/dialog/index")['DialogHeader']
    'DialogTitle': typeof import("../components/ui/dialog/index")['DialogTitle']
    'DialogDescription': typeof import("../components/ui/dialog/index")['DialogDescription']
    'DialogContent': typeof import("../components/ui/dialog/index")['DialogContent']
    'DialogScrollContent': typeof import("../components/ui/dialog/index")['DialogScrollContent']
    'DialogFooter': typeof import("../components/ui/dialog/index")['DialogFooter']
    'DrawerPortal': typeof import("../components/ui/drawer/index")['DrawerPortal']
    'DrawerTrigger': typeof import("../components/ui/drawer/index")['DrawerTrigger']
    'DrawerClose': typeof import("../components/ui/drawer/index")['DrawerClose']
    'Drawer': typeof import("../components/ui/drawer/index")['Drawer']
    'DrawerOverlay': typeof import("../components/ui/drawer/index")['DrawerOverlay']
    'DrawerContent': typeof import("../components/ui/drawer/index")['DrawerContent']
    'DrawerHeader': typeof import("../components/ui/drawer/index")['DrawerHeader']
    'DrawerFooter': typeof import("../components/ui/drawer/index")['DrawerFooter']
    'DrawerTitle': typeof import("../components/ui/drawer/index")['DrawerTitle']
    'DrawerDescription': typeof import("../components/ui/drawer/index")['DrawerDescription']
    'DropdownMenuPortal': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuPortal']
    'DropdownMenu': typeof import("../components/ui/dropdown-menu/index")['DropdownMenu']
    'DropdownMenuTrigger': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuTrigger']
    'DropdownMenuContent': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuContent']
    'DropdownMenuGroup': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuGroup']
    'DropdownMenuRadioGroup': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioGroup']
    'DropdownMenuItem': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuItem']
    'DropdownMenuCheckboxItem': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuCheckboxItem']
    'DropdownMenuRadioItem': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioItem']
    'DropdownMenuShortcut': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuShortcut']
    'DropdownMenuSeparator': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSeparator']
    'DropdownMenuLabel': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuLabel']
    'DropdownMenuSub': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSub']
    'DropdownMenuSubTrigger': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubTrigger']
    'DropdownMenuSubContent': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubContent']
    'Input': typeof import("../components/ui/input/index")['Input']
    'Label': typeof import("../components/ui/label/index")['Label']
    'Pagination': typeof import("../components/ui/pagination/index")['Pagination']
    'PaginationList': typeof import("../components/ui/pagination/index")['PaginationList']
    'PaginationListItem': typeof import("../components/ui/pagination/index")['PaginationListItem']
    'PaginationEllipsis': typeof import("../components/ui/pagination/index")['PaginationEllipsis']
    'PaginationFirst': typeof import("../components/ui/pagination/index")['PaginationFirst']
    'PaginationLast': typeof import("../components/ui/pagination/index")['PaginationLast']
    'PaginationNext': typeof import("../components/ui/pagination/index")['PaginationNext']
    'PaginationPrev': typeof import("../components/ui/pagination/index")['PaginationPrev']
    'Progress': typeof import("../components/ui/progress/index")['Progress']
    'ScrollArea': typeof import("../components/ui/scroll-area/index")['ScrollArea']
    'ScrollBar': typeof import("../components/ui/scroll-area/index")['ScrollBar']
    'Select': typeof import("../components/ui/select/index")['Select']
    'SelectValue': typeof import("../components/ui/select/index")['SelectValue']
    'SelectTrigger': typeof import("../components/ui/select/index")['SelectTrigger']
    'SelectContent': typeof import("../components/ui/select/index")['SelectContent']
    'SelectGroup': typeof import("../components/ui/select/index")['SelectGroup']
    'SelectItem': typeof import("../components/ui/select/index")['SelectItem']
    'SelectItemText': typeof import("../components/ui/select/index")['SelectItemText']
    'SelectLabel': typeof import("../components/ui/select/index")['SelectLabel']
    'SelectSeparator': typeof import("../components/ui/select/index")['SelectSeparator']
    'SelectScrollUpButton': typeof import("../components/ui/select/index")['SelectScrollUpButton']
    'SelectScrollDownButton': typeof import("../components/ui/select/index")['SelectScrollDownButton']
    'Separator': typeof import("../components/ui/separator/index")['Separator']
    'Sheet': typeof import("../components/ui/sheet/index")['Sheet']
    'SheetClose': typeof import("../components/ui/sheet/index")['SheetClose']
    'SheetContent': typeof import("../components/ui/sheet/index")['SheetContent']
    'SheetDescription': typeof import("../components/ui/sheet/index")['SheetDescription']
    'SheetFooter': typeof import("../components/ui/sheet/index")['SheetFooter']
    'SheetHeader': typeof import("../components/ui/sheet/index")['SheetHeader']
    'SheetTitle': typeof import("../components/ui/sheet/index")['SheetTitle']
    'SheetTrigger': typeof import("../components/ui/sheet/index")['SheetTrigger']
    'Sidebar': typeof import("../components/ui/sidebar/index")['Sidebar']
    'SidebarContent': typeof import("../components/ui/sidebar/index")['SidebarContent']
    'SidebarFooter': typeof import("../components/ui/sidebar/index")['SidebarFooter']
    'SidebarGroup': typeof import("../components/ui/sidebar/index")['SidebarGroup']
    'SidebarGroupAction': typeof import("../components/ui/sidebar/index")['SidebarGroupAction']
    'SidebarGroupContent': typeof import("../components/ui/sidebar/index")['SidebarGroupContent']
    'SidebarGroupLabel': typeof import("../components/ui/sidebar/index")['SidebarGroupLabel']
    'SidebarHeader': typeof import("../components/ui/sidebar/index")['SidebarHeader']
    'SidebarInput': typeof import("../components/ui/sidebar/index")['SidebarInput']
    'SidebarInset': typeof import("../components/ui/sidebar/index")['SidebarInset']
    'SidebarMenuAction': typeof import("../components/ui/sidebar/index")['SidebarMenuAction']
    'SidebarMenuBadge': typeof import("../components/ui/sidebar/index")['SidebarMenuBadge']
    'SidebarMenuButton': typeof import("../components/ui/sidebar/index")['SidebarMenuButton']
    'SidebarMenuItem': typeof import("../components/ui/sidebar/index")['SidebarMenuItem']
    'SidebarMenuSkeleton': typeof import("../components/ui/sidebar/index")['SidebarMenuSkeleton']
    'SidebarMenuSub': typeof import("../components/ui/sidebar/index")['SidebarMenuSub']
    'SidebarMenuSubButton': typeof import("../components/ui/sidebar/index")['SidebarMenuSubButton']
    'SidebarMenuSubItem': typeof import("../components/ui/sidebar/index")['SidebarMenuSubItem']
    'SidebarProvider': typeof import("../components/ui/sidebar/index")['SidebarProvider']
    'SidebarRail': typeof import("../components/ui/sidebar/index")['SidebarRail']
    'SidebarSeparator': typeof import("../components/ui/sidebar/index")['SidebarSeparator']
    'SidebarTrigger': typeof import("../components/ui/sidebar/index")['SidebarTrigger']
    'Skeleton': typeof import("../components/ui/skeleton/index")['Skeleton']
    'Switch': typeof import("../components/ui/switch/index")['Switch']
    'Table': typeof import("../components/ui/table/index")['Table']
    'TableBody': typeof import("../components/ui/table/index")['TableBody']
    'TableCell': typeof import("../components/ui/table/index")['TableCell']
    'TableHead': typeof import("../components/ui/table/index")['TableHead']
    'TableHeader': typeof import("../components/ui/table/index")['TableHeader']
    'TableFooter': typeof import("../components/ui/table/index")['TableFooter']
    'TableRow': typeof import("../components/ui/table/index")['TableRow']
    'TableCaption': typeof import("../components/ui/table/index")['TableCaption']
    'TableEmpty': typeof import("../components/ui/table/index")['TableEmpty']
    'Tabs': typeof import("../components/ui/tabs/index")['Tabs']
    'TabsTrigger': typeof import("../components/ui/tabs/index")['TabsTrigger']
    'TabsList': typeof import("../components/ui/tabs/index")['TabsList']
    'TabsContent': typeof import("../components/ui/tabs/index")['TabsContent']
    'Tooltip': typeof import("../components/ui/tooltip/index")['Tooltip']
    'TooltipContent': typeof import("../components/ui/tooltip/index")['TooltipContent']
    'TooltipProvider': typeof import("../components/ui/tooltip/index")['TooltipProvider']
    'TooltipTrigger': typeof import("../components/ui/tooltip/index")['TooltipTrigger']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'UModals': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
    'USlideovers': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyCardAssetCard': typeof import("../components/Card/AssetCard.vue")['default']
    'LazyHeaderCustomMenu': typeof import("../components/Header/CustomMenu.vue")['default']
    'LazyHeaderMenu': typeof import("../components/Header/Menu.vue")['default']
    'LazyModalCreateProduct': typeof import("../components/Modal/createProduct.vue")['default']
    'LazyModalProductModal': typeof import("../components/Modal/productModal.vue")['default']
    'LazyProductAddQuantity': typeof import("../components/Product/AddQuantity.vue")['default']
    'LazySidebarCustomMenu': typeof import("../components/Sidebar/CustomMenu.vue")['default']
    'LazySidebarMenu': typeof import("../components/Sidebar/Menu.vue")['default']
    'LazyTableAssetActiveTable': typeof import("../components/Table/Asset/ActiveTable.vue")['default']
    'LazyTableAssetBrokenTable': typeof import("../components/Table/Asset/BrokenTable.vue")['default']
    'LazyTableAssetInactiveTable': typeof import("../components/Table/Asset/InactiveTable.vue")['default']
    'LazyTableAssetOver250': typeof import("../components/Table/Asset/over250.vue")['default']
    'LazyTableAssetUnder250': typeof import("../components/Table/Asset/under250.vue")['default']
    'LazyTableRepair': typeof import("../components/Table/Repair/Repair.vue")['default']
    'LazyTableTaskMonthlyTable': typeof import("../components/Table/Task/MonthlyTable.vue")['default']
    'LazyTableTaskTodayTable': typeof import("../components/Table/Task/TodayTable.vue")['default']
    'LazyTableTaskWeeklyTable': typeof import("../components/Table/Task/WeeklyTable.vue")['default']
    'LazyUtilsValueUpdater': typeof import("../components/utils/valueUpdater.vue")['default']
    'LazyUAccordion': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Accordion.vue")['default']
    'LazyUAlert': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Alert.vue")['default']
    'LazyUAvatar': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Avatar.vue")['default']
    'LazyUAvatarGroup': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/AvatarGroup")['default']
    'LazyUBadge': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Badge.vue")['default']
    'LazyUButton': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Button.vue")['default']
    'LazyUButtonGroup': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/ButtonGroup")['default']
    'LazyUCarousel': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Carousel.vue")['default']
    'LazyUChip': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Chip.vue")['default']
    'LazyUDropdown': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Dropdown.vue")['default']
    'LazyUIcon': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Icon.vue")['default']
    'LazyUKbd': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Kbd.vue")['default']
    'LazyULink': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Link.vue")['default']
    'LazyUMeter': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Meter.vue")['default']
    'LazyUMeterGroup': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/MeterGroup")['default']
    'LazyUProgress': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Progress.vue")['default']
    'LazyUCheckbox': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Checkbox.vue")['default']
    'LazyUForm': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Form.vue")['default']
    'LazyUFormGroup': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/FormGroup.vue")['default']
    'LazyUInput': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Input.vue")['default']
    'LazyUInputMenu': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/InputMenu.vue")['default']
    'LazyURadio': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Radio.vue")['default']
    'LazyURadioGroup': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/RadioGroup.vue")['default']
    'LazyURange': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Range.vue")['default']
    'LazyUSelect': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Select.vue")['default']
    'LazyUSelectMenu': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/SelectMenu.vue")['default']
    'LazyUTextarea': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Textarea.vue")['default']
    'LazyUToggle': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Toggle.vue")['default']
    'LazyUTable': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/data/Table.vue")['default']
    'LazyUCard': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Card.vue")['default']
    'LazyUContainer': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Container.vue")['default']
    'LazyUDivider': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Divider.vue")['default']
    'LazyUSkeleton': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Skeleton.vue")['default']
    'LazyUBreadcrumb': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/Breadcrumb.vue")['default']
    'LazyUCommandPalette': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/CommandPalette.vue")['default']
    'LazyUCommandPaletteGroup': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/CommandPaletteGroup.vue")['default']
    'LazyUHorizontalNavigation': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/HorizontalNavigation.vue")['default']
    'LazyUPagination': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/Pagination.vue")['default']
    'LazyUTabs': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/Tabs.vue")['default']
    'LazyUVerticalNavigation': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/VerticalNavigation.vue")['default']
    'LazyUContextMenu': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/ContextMenu.vue")['default']
    'LazyUModal': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Modal.vue")['default']
    'LazyUModals': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Modals.client.vue")['default']
    'LazyUNotification': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Notification.vue")['default']
    'LazyUNotifications': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Notifications.vue")['default']
    'LazyUPopover': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Popover.vue")['default']
    'LazyUSlideover': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Slideover.vue")['default']
    'LazyUSlideovers': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Slideovers.client.vue")['default']
    'LazyUTooltip': typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Tooltip.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyIcon': typeof import("../node_modules/@nuxt/icon/dist/runtime/components/index")['default']
    'LazyColorScheme': typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
    'LazyAccordion': typeof import("../components/ui/accordion/index")['Accordion']
    'LazyAccordionContent': typeof import("../components/ui/accordion/index")['AccordionContent']
    'LazyAccordionItem': typeof import("../components/ui/accordion/index")['AccordionItem']
    'LazyAccordionTrigger': typeof import("../components/ui/accordion/index")['AccordionTrigger']
    'LazyBadge': typeof import("../components/ui/badge/index")['Badge']
    'LazyBreadcrumb': typeof import("../components/ui/breadcrumb/index")['Breadcrumb']
    'LazyBreadcrumbEllipsis': typeof import("../components/ui/breadcrumb/index")['BreadcrumbEllipsis']
    'LazyBreadcrumbItem': typeof import("../components/ui/breadcrumb/index")['BreadcrumbItem']
    'LazyBreadcrumbLink': typeof import("../components/ui/breadcrumb/index")['BreadcrumbLink']
    'LazyBreadcrumbList': typeof import("../components/ui/breadcrumb/index")['BreadcrumbList']
    'LazyBreadcrumbPage': typeof import("../components/ui/breadcrumb/index")['BreadcrumbPage']
    'LazyBreadcrumbSeparator': typeof import("../components/ui/breadcrumb/index")['BreadcrumbSeparator']
    'LazyButton': typeof import("../components/ui/button/index")['Button']
    'LazyCard': typeof import("../components/ui/card/index")['Card']
    'LazyCardHeader': typeof import("../components/ui/card/index")['CardHeader']
    'LazyCardTitle': typeof import("../components/ui/card/index")['CardTitle']
    'LazyCardDescription': typeof import("../components/ui/card/index")['CardDescription']
    'LazyCardContent': typeof import("../components/ui/card/index")['CardContent']
    'LazyCardFooter': typeof import("../components/ui/card/index")['CardFooter']
    'LazyChartTooltip': typeof import("../components/ui/chart/index")['ChartTooltip']
    'LazyChartSingleTooltip': typeof import("../components/ui/chart/index")['ChartSingleTooltip']
    'LazyChartLegend': typeof import("../components/ui/chart/index")['ChartLegend']
    'LazyChartCrosshair': typeof import("../components/ui/chart/index")['ChartCrosshair']
    'LazyBarChart': typeof import("../components/ui/chart-bar/index")['BarChart']
    'LazyDonutChart': typeof import("../components/ui/chart-donut/index")['DonutChart']
    'LazyCheckbox': typeof import("../components/ui/checkbox/index")['Checkbox']
    'LazyCollapsible': typeof import("../components/ui/collapsible/index")['Collapsible']
    'LazyCollapsibleContent': typeof import("../components/ui/collapsible/index")['CollapsibleContent']
    'LazyCollapsibleTrigger': typeof import("../components/ui/collapsible/index")['CollapsibleTrigger']
    'LazyDialog': typeof import("../components/ui/dialog/index")['Dialog']
    'LazyDialogClose': typeof import("../components/ui/dialog/index")['DialogClose']
    'LazyDialogTrigger': typeof import("../components/ui/dialog/index")['DialogTrigger']
    'LazyDialogHeader': typeof import("../components/ui/dialog/index")['DialogHeader']
    'LazyDialogTitle': typeof import("../components/ui/dialog/index")['DialogTitle']
    'LazyDialogDescription': typeof import("../components/ui/dialog/index")['DialogDescription']
    'LazyDialogContent': typeof import("../components/ui/dialog/index")['DialogContent']
    'LazyDialogScrollContent': typeof import("../components/ui/dialog/index")['DialogScrollContent']
    'LazyDialogFooter': typeof import("../components/ui/dialog/index")['DialogFooter']
    'LazyDrawerPortal': typeof import("../components/ui/drawer/index")['DrawerPortal']
    'LazyDrawerTrigger': typeof import("../components/ui/drawer/index")['DrawerTrigger']
    'LazyDrawerClose': typeof import("../components/ui/drawer/index")['DrawerClose']
    'LazyDrawer': typeof import("../components/ui/drawer/index")['Drawer']
    'LazyDrawerOverlay': typeof import("../components/ui/drawer/index")['DrawerOverlay']
    'LazyDrawerContent': typeof import("../components/ui/drawer/index")['DrawerContent']
    'LazyDrawerHeader': typeof import("../components/ui/drawer/index")['DrawerHeader']
    'LazyDrawerFooter': typeof import("../components/ui/drawer/index")['DrawerFooter']
    'LazyDrawerTitle': typeof import("../components/ui/drawer/index")['DrawerTitle']
    'LazyDrawerDescription': typeof import("../components/ui/drawer/index")['DrawerDescription']
    'LazyDropdownMenuPortal': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuPortal']
    'LazyDropdownMenu': typeof import("../components/ui/dropdown-menu/index")['DropdownMenu']
    'LazyDropdownMenuTrigger': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuTrigger']
    'LazyDropdownMenuContent': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuContent']
    'LazyDropdownMenuGroup': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuGroup']
    'LazyDropdownMenuRadioGroup': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioGroup']
    'LazyDropdownMenuItem': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuItem']
    'LazyDropdownMenuCheckboxItem': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuCheckboxItem']
    'LazyDropdownMenuRadioItem': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioItem']
    'LazyDropdownMenuShortcut': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuShortcut']
    'LazyDropdownMenuSeparator': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSeparator']
    'LazyDropdownMenuLabel': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuLabel']
    'LazyDropdownMenuSub': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSub']
    'LazyDropdownMenuSubTrigger': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubTrigger']
    'LazyDropdownMenuSubContent': typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubContent']
    'LazyInput': typeof import("../components/ui/input/index")['Input']
    'LazyLabel': typeof import("../components/ui/label/index")['Label']
    'LazyPagination': typeof import("../components/ui/pagination/index")['Pagination']
    'LazyPaginationList': typeof import("../components/ui/pagination/index")['PaginationList']
    'LazyPaginationListItem': typeof import("../components/ui/pagination/index")['PaginationListItem']
    'LazyPaginationEllipsis': typeof import("../components/ui/pagination/index")['PaginationEllipsis']
    'LazyPaginationFirst': typeof import("../components/ui/pagination/index")['PaginationFirst']
    'LazyPaginationLast': typeof import("../components/ui/pagination/index")['PaginationLast']
    'LazyPaginationNext': typeof import("../components/ui/pagination/index")['PaginationNext']
    'LazyPaginationPrev': typeof import("../components/ui/pagination/index")['PaginationPrev']
    'LazyProgress': typeof import("../components/ui/progress/index")['Progress']
    'LazyScrollArea': typeof import("../components/ui/scroll-area/index")['ScrollArea']
    'LazyScrollBar': typeof import("../components/ui/scroll-area/index")['ScrollBar']
    'LazySelect': typeof import("../components/ui/select/index")['Select']
    'LazySelectValue': typeof import("../components/ui/select/index")['SelectValue']
    'LazySelectTrigger': typeof import("../components/ui/select/index")['SelectTrigger']
    'LazySelectContent': typeof import("../components/ui/select/index")['SelectContent']
    'LazySelectGroup': typeof import("../components/ui/select/index")['SelectGroup']
    'LazySelectItem': typeof import("../components/ui/select/index")['SelectItem']
    'LazySelectItemText': typeof import("../components/ui/select/index")['SelectItemText']
    'LazySelectLabel': typeof import("../components/ui/select/index")['SelectLabel']
    'LazySelectSeparator': typeof import("../components/ui/select/index")['SelectSeparator']
    'LazySelectScrollUpButton': typeof import("../components/ui/select/index")['SelectScrollUpButton']
    'LazySelectScrollDownButton': typeof import("../components/ui/select/index")['SelectScrollDownButton']
    'LazySeparator': typeof import("../components/ui/separator/index")['Separator']
    'LazySheet': typeof import("../components/ui/sheet/index")['Sheet']
    'LazySheetClose': typeof import("../components/ui/sheet/index")['SheetClose']
    'LazySheetContent': typeof import("../components/ui/sheet/index")['SheetContent']
    'LazySheetDescription': typeof import("../components/ui/sheet/index")['SheetDescription']
    'LazySheetFooter': typeof import("../components/ui/sheet/index")['SheetFooter']
    'LazySheetHeader': typeof import("../components/ui/sheet/index")['SheetHeader']
    'LazySheetTitle': typeof import("../components/ui/sheet/index")['SheetTitle']
    'LazySheetTrigger': typeof import("../components/ui/sheet/index")['SheetTrigger']
    'LazySidebar': typeof import("../components/ui/sidebar/index")['Sidebar']
    'LazySidebarContent': typeof import("../components/ui/sidebar/index")['SidebarContent']
    'LazySidebarFooter': typeof import("../components/ui/sidebar/index")['SidebarFooter']
    'LazySidebarGroup': typeof import("../components/ui/sidebar/index")['SidebarGroup']
    'LazySidebarGroupAction': typeof import("../components/ui/sidebar/index")['SidebarGroupAction']
    'LazySidebarGroupContent': typeof import("../components/ui/sidebar/index")['SidebarGroupContent']
    'LazySidebarGroupLabel': typeof import("../components/ui/sidebar/index")['SidebarGroupLabel']
    'LazySidebarHeader': typeof import("../components/ui/sidebar/index")['SidebarHeader']
    'LazySidebarInput': typeof import("../components/ui/sidebar/index")['SidebarInput']
    'LazySidebarInset': typeof import("../components/ui/sidebar/index")['SidebarInset']
    'LazySidebarMenuAction': typeof import("../components/ui/sidebar/index")['SidebarMenuAction']
    'LazySidebarMenuBadge': typeof import("../components/ui/sidebar/index")['SidebarMenuBadge']
    'LazySidebarMenuButton': typeof import("../components/ui/sidebar/index")['SidebarMenuButton']
    'LazySidebarMenuItem': typeof import("../components/ui/sidebar/index")['SidebarMenuItem']
    'LazySidebarMenuSkeleton': typeof import("../components/ui/sidebar/index")['SidebarMenuSkeleton']
    'LazySidebarMenuSub': typeof import("../components/ui/sidebar/index")['SidebarMenuSub']
    'LazySidebarMenuSubButton': typeof import("../components/ui/sidebar/index")['SidebarMenuSubButton']
    'LazySidebarMenuSubItem': typeof import("../components/ui/sidebar/index")['SidebarMenuSubItem']
    'LazySidebarProvider': typeof import("../components/ui/sidebar/index")['SidebarProvider']
    'LazySidebarRail': typeof import("../components/ui/sidebar/index")['SidebarRail']
    'LazySidebarSeparator': typeof import("../components/ui/sidebar/index")['SidebarSeparator']
    'LazySidebarTrigger': typeof import("../components/ui/sidebar/index")['SidebarTrigger']
    'LazySkeleton': typeof import("../components/ui/skeleton/index")['Skeleton']
    'LazySwitch': typeof import("../components/ui/switch/index")['Switch']
    'LazyTable': typeof import("../components/ui/table/index")['Table']
    'LazyTableBody': typeof import("../components/ui/table/index")['TableBody']
    'LazyTableCell': typeof import("../components/ui/table/index")['TableCell']
    'LazyTableHead': typeof import("../components/ui/table/index")['TableHead']
    'LazyTableHeader': typeof import("../components/ui/table/index")['TableHeader']
    'LazyTableFooter': typeof import("../components/ui/table/index")['TableFooter']
    'LazyTableRow': typeof import("../components/ui/table/index")['TableRow']
    'LazyTableCaption': typeof import("../components/ui/table/index")['TableCaption']
    'LazyTableEmpty': typeof import("../components/ui/table/index")['TableEmpty']
    'LazyTabs': typeof import("../components/ui/tabs/index")['Tabs']
    'LazyTabsTrigger': typeof import("../components/ui/tabs/index")['TabsTrigger']
    'LazyTabsList': typeof import("../components/ui/tabs/index")['TabsList']
    'LazyTabsContent': typeof import("../components/ui/tabs/index")['TabsContent']
    'LazyTooltip': typeof import("../components/ui/tooltip/index")['Tooltip']
    'LazyTooltipContent': typeof import("../components/ui/tooltip/index")['TooltipContent']
    'LazyTooltipProvider': typeof import("../components/ui/tooltip/index")['TooltipProvider']
    'LazyTooltipTrigger': typeof import("../components/ui/tooltip/index")['TooltipTrigger']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyUModals': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
    'LazyUSlideovers': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const CardAssetCard: typeof import("../components/Card/AssetCard.vue")['default']
export const HeaderCustomMenu: typeof import("../components/Header/CustomMenu.vue")['default']
export const HeaderMenu: typeof import("../components/Header/Menu.vue")['default']
export const ModalCreateProduct: typeof import("../components/Modal/createProduct.vue")['default']
export const ModalProductModal: typeof import("../components/Modal/productModal.vue")['default']
export const ProductAddQuantity: typeof import("../components/Product/AddQuantity.vue")['default']
export const SidebarCustomMenu: typeof import("../components/Sidebar/CustomMenu.vue")['default']
export const SidebarMenu: typeof import("../components/Sidebar/Menu.vue")['default']
export const TableAssetActiveTable: typeof import("../components/Table/Asset/ActiveTable.vue")['default']
export const TableAssetBrokenTable: typeof import("../components/Table/Asset/BrokenTable.vue")['default']
export const TableAssetInactiveTable: typeof import("../components/Table/Asset/InactiveTable.vue")['default']
export const TableAssetOver250: typeof import("../components/Table/Asset/over250.vue")['default']
export const TableAssetUnder250: typeof import("../components/Table/Asset/under250.vue")['default']
export const TableRepair: typeof import("../components/Table/Repair/Repair.vue")['default']
export const TableTaskMonthlyTable: typeof import("../components/Table/Task/MonthlyTable.vue")['default']
export const TableTaskTodayTable: typeof import("../components/Table/Task/TodayTable.vue")['default']
export const TableTaskWeeklyTable: typeof import("../components/Table/Task/WeeklyTable.vue")['default']
export const UtilsValueUpdater: typeof import("../components/utils/valueUpdater.vue")['default']
export const UAccordion: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Accordion.vue")['default']
export const UAlert: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Alert.vue")['default']
export const UAvatar: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Avatar.vue")['default']
export const UAvatarGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/AvatarGroup")['default']
export const UBadge: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Badge.vue")['default']
export const UButton: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Button.vue")['default']
export const UButtonGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/ButtonGroup")['default']
export const UCarousel: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Carousel.vue")['default']
export const UChip: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Chip.vue")['default']
export const UDropdown: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Dropdown.vue")['default']
export const UIcon: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Icon.vue")['default']
export const UKbd: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Kbd.vue")['default']
export const ULink: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Link.vue")['default']
export const UMeter: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Meter.vue")['default']
export const UMeterGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/MeterGroup")['default']
export const UProgress: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Progress.vue")['default']
export const UCheckbox: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Checkbox.vue")['default']
export const UForm: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Form.vue")['default']
export const UFormGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/FormGroup.vue")['default']
export const UInput: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Input.vue")['default']
export const UInputMenu: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/InputMenu.vue")['default']
export const URadio: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Radio.vue")['default']
export const URadioGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/RadioGroup.vue")['default']
export const URange: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Range.vue")['default']
export const USelect: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Select.vue")['default']
export const USelectMenu: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/SelectMenu.vue")['default']
export const UTextarea: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Textarea.vue")['default']
export const UToggle: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Toggle.vue")['default']
export const UTable: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/data/Table.vue")['default']
export const UCard: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Card.vue")['default']
export const UContainer: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Container.vue")['default']
export const UDivider: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Divider.vue")['default']
export const USkeleton: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Skeleton.vue")['default']
export const UBreadcrumb: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/Breadcrumb.vue")['default']
export const UCommandPalette: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/CommandPalette.vue")['default']
export const UCommandPaletteGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/CommandPaletteGroup.vue")['default']
export const UHorizontalNavigation: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/HorizontalNavigation.vue")['default']
export const UPagination: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/Pagination.vue")['default']
export const UTabs: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/Tabs.vue")['default']
export const UVerticalNavigation: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/VerticalNavigation.vue")['default']
export const UContextMenu: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/ContextMenu.vue")['default']
export const UModal: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Modal.vue")['default']
export const UModals: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Modals.client.vue")['default']
export const UNotification: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Notification.vue")['default']
export const UNotifications: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Notifications.vue")['default']
export const UPopover: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Popover.vue")['default']
export const USlideover: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Slideover.vue")['default']
export const USlideovers: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Slideovers.client.vue")['default']
export const UTooltip: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Tooltip.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const Icon: typeof import("../node_modules/@nuxt/icon/dist/runtime/components/index")['default']
export const ColorScheme: typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
export const Accordion: typeof import("../components/ui/accordion/index")['Accordion']
export const AccordionContent: typeof import("../components/ui/accordion/index")['AccordionContent']
export const AccordionItem: typeof import("../components/ui/accordion/index")['AccordionItem']
export const AccordionTrigger: typeof import("../components/ui/accordion/index")['AccordionTrigger']
export const Badge: typeof import("../components/ui/badge/index")['Badge']
export const Breadcrumb: typeof import("../components/ui/breadcrumb/index")['Breadcrumb']
export const BreadcrumbEllipsis: typeof import("../components/ui/breadcrumb/index")['BreadcrumbEllipsis']
export const BreadcrumbItem: typeof import("../components/ui/breadcrumb/index")['BreadcrumbItem']
export const BreadcrumbLink: typeof import("../components/ui/breadcrumb/index")['BreadcrumbLink']
export const BreadcrumbList: typeof import("../components/ui/breadcrumb/index")['BreadcrumbList']
export const BreadcrumbPage: typeof import("../components/ui/breadcrumb/index")['BreadcrumbPage']
export const BreadcrumbSeparator: typeof import("../components/ui/breadcrumb/index")['BreadcrumbSeparator']
export const Button: typeof import("../components/ui/button/index")['Button']
export const Card: typeof import("../components/ui/card/index")['Card']
export const CardHeader: typeof import("../components/ui/card/index")['CardHeader']
export const CardTitle: typeof import("../components/ui/card/index")['CardTitle']
export const CardDescription: typeof import("../components/ui/card/index")['CardDescription']
export const CardContent: typeof import("../components/ui/card/index")['CardContent']
export const CardFooter: typeof import("../components/ui/card/index")['CardFooter']
export const ChartTooltip: typeof import("../components/ui/chart/index")['ChartTooltip']
export const ChartSingleTooltip: typeof import("../components/ui/chart/index")['ChartSingleTooltip']
export const ChartLegend: typeof import("../components/ui/chart/index")['ChartLegend']
export const ChartCrosshair: typeof import("../components/ui/chart/index")['ChartCrosshair']
export const BarChart: typeof import("../components/ui/chart-bar/index")['BarChart']
export const DonutChart: typeof import("../components/ui/chart-donut/index")['DonutChart']
export const Checkbox: typeof import("../components/ui/checkbox/index")['Checkbox']
export const Collapsible: typeof import("../components/ui/collapsible/index")['Collapsible']
export const CollapsibleContent: typeof import("../components/ui/collapsible/index")['CollapsibleContent']
export const CollapsibleTrigger: typeof import("../components/ui/collapsible/index")['CollapsibleTrigger']
export const Dialog: typeof import("../components/ui/dialog/index")['Dialog']
export const DialogClose: typeof import("../components/ui/dialog/index")['DialogClose']
export const DialogTrigger: typeof import("../components/ui/dialog/index")['DialogTrigger']
export const DialogHeader: typeof import("../components/ui/dialog/index")['DialogHeader']
export const DialogTitle: typeof import("../components/ui/dialog/index")['DialogTitle']
export const DialogDescription: typeof import("../components/ui/dialog/index")['DialogDescription']
export const DialogContent: typeof import("../components/ui/dialog/index")['DialogContent']
export const DialogScrollContent: typeof import("../components/ui/dialog/index")['DialogScrollContent']
export const DialogFooter: typeof import("../components/ui/dialog/index")['DialogFooter']
export const DrawerPortal: typeof import("../components/ui/drawer/index")['DrawerPortal']
export const DrawerTrigger: typeof import("../components/ui/drawer/index")['DrawerTrigger']
export const DrawerClose: typeof import("../components/ui/drawer/index")['DrawerClose']
export const Drawer: typeof import("../components/ui/drawer/index")['Drawer']
export const DrawerOverlay: typeof import("../components/ui/drawer/index")['DrawerOverlay']
export const DrawerContent: typeof import("../components/ui/drawer/index")['DrawerContent']
export const DrawerHeader: typeof import("../components/ui/drawer/index")['DrawerHeader']
export const DrawerFooter: typeof import("../components/ui/drawer/index")['DrawerFooter']
export const DrawerTitle: typeof import("../components/ui/drawer/index")['DrawerTitle']
export const DrawerDescription: typeof import("../components/ui/drawer/index")['DrawerDescription']
export const DropdownMenuPortal: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuPortal']
export const DropdownMenu: typeof import("../components/ui/dropdown-menu/index")['DropdownMenu']
export const DropdownMenuTrigger: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuTrigger']
export const DropdownMenuContent: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuContent']
export const DropdownMenuGroup: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuGroup']
export const DropdownMenuRadioGroup: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioGroup']
export const DropdownMenuItem: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuItem']
export const DropdownMenuCheckboxItem: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuCheckboxItem']
export const DropdownMenuRadioItem: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioItem']
export const DropdownMenuShortcut: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuShortcut']
export const DropdownMenuSeparator: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSeparator']
export const DropdownMenuLabel: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuLabel']
export const DropdownMenuSub: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSub']
export const DropdownMenuSubTrigger: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubTrigger']
export const DropdownMenuSubContent: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubContent']
export const Input: typeof import("../components/ui/input/index")['Input']
export const Label: typeof import("../components/ui/label/index")['Label']
export const Pagination: typeof import("../components/ui/pagination/index")['Pagination']
export const PaginationList: typeof import("../components/ui/pagination/index")['PaginationList']
export const PaginationListItem: typeof import("../components/ui/pagination/index")['PaginationListItem']
export const PaginationEllipsis: typeof import("../components/ui/pagination/index")['PaginationEllipsis']
export const PaginationFirst: typeof import("../components/ui/pagination/index")['PaginationFirst']
export const PaginationLast: typeof import("../components/ui/pagination/index")['PaginationLast']
export const PaginationNext: typeof import("../components/ui/pagination/index")['PaginationNext']
export const PaginationPrev: typeof import("../components/ui/pagination/index")['PaginationPrev']
export const Progress: typeof import("../components/ui/progress/index")['Progress']
export const ScrollArea: typeof import("../components/ui/scroll-area/index")['ScrollArea']
export const ScrollBar: typeof import("../components/ui/scroll-area/index")['ScrollBar']
export const Select: typeof import("../components/ui/select/index")['Select']
export const SelectValue: typeof import("../components/ui/select/index")['SelectValue']
export const SelectTrigger: typeof import("../components/ui/select/index")['SelectTrigger']
export const SelectContent: typeof import("../components/ui/select/index")['SelectContent']
export const SelectGroup: typeof import("../components/ui/select/index")['SelectGroup']
export const SelectItem: typeof import("../components/ui/select/index")['SelectItem']
export const SelectItemText: typeof import("../components/ui/select/index")['SelectItemText']
export const SelectLabel: typeof import("../components/ui/select/index")['SelectLabel']
export const SelectSeparator: typeof import("../components/ui/select/index")['SelectSeparator']
export const SelectScrollUpButton: typeof import("../components/ui/select/index")['SelectScrollUpButton']
export const SelectScrollDownButton: typeof import("../components/ui/select/index")['SelectScrollDownButton']
export const Separator: typeof import("../components/ui/separator/index")['Separator']
export const Sheet: typeof import("../components/ui/sheet/index")['Sheet']
export const SheetClose: typeof import("../components/ui/sheet/index")['SheetClose']
export const SheetContent: typeof import("../components/ui/sheet/index")['SheetContent']
export const SheetDescription: typeof import("../components/ui/sheet/index")['SheetDescription']
export const SheetFooter: typeof import("../components/ui/sheet/index")['SheetFooter']
export const SheetHeader: typeof import("../components/ui/sheet/index")['SheetHeader']
export const SheetTitle: typeof import("../components/ui/sheet/index")['SheetTitle']
export const SheetTrigger: typeof import("../components/ui/sheet/index")['SheetTrigger']
export const Sidebar: typeof import("../components/ui/sidebar/index")['Sidebar']
export const SidebarContent: typeof import("../components/ui/sidebar/index")['SidebarContent']
export const SidebarFooter: typeof import("../components/ui/sidebar/index")['SidebarFooter']
export const SidebarGroup: typeof import("../components/ui/sidebar/index")['SidebarGroup']
export const SidebarGroupAction: typeof import("../components/ui/sidebar/index")['SidebarGroupAction']
export const SidebarGroupContent: typeof import("../components/ui/sidebar/index")['SidebarGroupContent']
export const SidebarGroupLabel: typeof import("../components/ui/sidebar/index")['SidebarGroupLabel']
export const SidebarHeader: typeof import("../components/ui/sidebar/index")['SidebarHeader']
export const SidebarInput: typeof import("../components/ui/sidebar/index")['SidebarInput']
export const SidebarInset: typeof import("../components/ui/sidebar/index")['SidebarInset']
export const SidebarMenuAction: typeof import("../components/ui/sidebar/index")['SidebarMenuAction']
export const SidebarMenuBadge: typeof import("../components/ui/sidebar/index")['SidebarMenuBadge']
export const SidebarMenuButton: typeof import("../components/ui/sidebar/index")['SidebarMenuButton']
export const SidebarMenuItem: typeof import("../components/ui/sidebar/index")['SidebarMenuItem']
export const SidebarMenuSkeleton: typeof import("../components/ui/sidebar/index")['SidebarMenuSkeleton']
export const SidebarMenuSub: typeof import("../components/ui/sidebar/index")['SidebarMenuSub']
export const SidebarMenuSubButton: typeof import("../components/ui/sidebar/index")['SidebarMenuSubButton']
export const SidebarMenuSubItem: typeof import("../components/ui/sidebar/index")['SidebarMenuSubItem']
export const SidebarProvider: typeof import("../components/ui/sidebar/index")['SidebarProvider']
export const SidebarRail: typeof import("../components/ui/sidebar/index")['SidebarRail']
export const SidebarSeparator: typeof import("../components/ui/sidebar/index")['SidebarSeparator']
export const SidebarTrigger: typeof import("../components/ui/sidebar/index")['SidebarTrigger']
export const Skeleton: typeof import("../components/ui/skeleton/index")['Skeleton']
export const Switch: typeof import("../components/ui/switch/index")['Switch']
export const Table: typeof import("../components/ui/table/index")['Table']
export const TableBody: typeof import("../components/ui/table/index")['TableBody']
export const TableCell: typeof import("../components/ui/table/index")['TableCell']
export const TableHead: typeof import("../components/ui/table/index")['TableHead']
export const TableHeader: typeof import("../components/ui/table/index")['TableHeader']
export const TableFooter: typeof import("../components/ui/table/index")['TableFooter']
export const TableRow: typeof import("../components/ui/table/index")['TableRow']
export const TableCaption: typeof import("../components/ui/table/index")['TableCaption']
export const TableEmpty: typeof import("../components/ui/table/index")['TableEmpty']
export const Tabs: typeof import("../components/ui/tabs/index")['Tabs']
export const TabsTrigger: typeof import("../components/ui/tabs/index")['TabsTrigger']
export const TabsList: typeof import("../components/ui/tabs/index")['TabsList']
export const TabsContent: typeof import("../components/ui/tabs/index")['TabsContent']
export const Tooltip: typeof import("../components/ui/tooltip/index")['Tooltip']
export const TooltipContent: typeof import("../components/ui/tooltip/index")['TooltipContent']
export const TooltipProvider: typeof import("../components/ui/tooltip/index")['TooltipProvider']
export const TooltipTrigger: typeof import("../components/ui/tooltip/index")['TooltipTrigger']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const UModals: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const USlideovers: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyCardAssetCard: typeof import("../components/Card/AssetCard.vue")['default']
export const LazyHeaderCustomMenu: typeof import("../components/Header/CustomMenu.vue")['default']
export const LazyHeaderMenu: typeof import("../components/Header/Menu.vue")['default']
export const LazyModalCreateProduct: typeof import("../components/Modal/createProduct.vue")['default']
export const LazyModalProductModal: typeof import("../components/Modal/productModal.vue")['default']
export const LazyProductAddQuantity: typeof import("../components/Product/AddQuantity.vue")['default']
export const LazySidebarCustomMenu: typeof import("../components/Sidebar/CustomMenu.vue")['default']
export const LazySidebarMenu: typeof import("../components/Sidebar/Menu.vue")['default']
export const LazyTableAssetActiveTable: typeof import("../components/Table/Asset/ActiveTable.vue")['default']
export const LazyTableAssetBrokenTable: typeof import("../components/Table/Asset/BrokenTable.vue")['default']
export const LazyTableAssetInactiveTable: typeof import("../components/Table/Asset/InactiveTable.vue")['default']
export const LazyTableAssetOver250: typeof import("../components/Table/Asset/over250.vue")['default']
export const LazyTableAssetUnder250: typeof import("../components/Table/Asset/under250.vue")['default']
export const LazyTableRepair: typeof import("../components/Table/Repair/Repair.vue")['default']
export const LazyTableTaskMonthlyTable: typeof import("../components/Table/Task/MonthlyTable.vue")['default']
export const LazyTableTaskTodayTable: typeof import("../components/Table/Task/TodayTable.vue")['default']
export const LazyTableTaskWeeklyTable: typeof import("../components/Table/Task/WeeklyTable.vue")['default']
export const LazyUtilsValueUpdater: typeof import("../components/utils/valueUpdater.vue")['default']
export const LazyUAccordion: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Accordion.vue")['default']
export const LazyUAlert: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Alert.vue")['default']
export const LazyUAvatar: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Avatar.vue")['default']
export const LazyUAvatarGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/AvatarGroup")['default']
export const LazyUBadge: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Badge.vue")['default']
export const LazyUButton: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Button.vue")['default']
export const LazyUButtonGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/ButtonGroup")['default']
export const LazyUCarousel: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Carousel.vue")['default']
export const LazyUChip: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Chip.vue")['default']
export const LazyUDropdown: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Dropdown.vue")['default']
export const LazyUIcon: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Icon.vue")['default']
export const LazyUKbd: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Kbd.vue")['default']
export const LazyULink: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Link.vue")['default']
export const LazyUMeter: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Meter.vue")['default']
export const LazyUMeterGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/MeterGroup")['default']
export const LazyUProgress: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/elements/Progress.vue")['default']
export const LazyUCheckbox: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Checkbox.vue")['default']
export const LazyUForm: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Form.vue")['default']
export const LazyUFormGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/FormGroup.vue")['default']
export const LazyUInput: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Input.vue")['default']
export const LazyUInputMenu: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/InputMenu.vue")['default']
export const LazyURadio: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Radio.vue")['default']
export const LazyURadioGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/RadioGroup.vue")['default']
export const LazyURange: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Range.vue")['default']
export const LazyUSelect: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Select.vue")['default']
export const LazyUSelectMenu: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/SelectMenu.vue")['default']
export const LazyUTextarea: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Textarea.vue")['default']
export const LazyUToggle: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/forms/Toggle.vue")['default']
export const LazyUTable: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/data/Table.vue")['default']
export const LazyUCard: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Card.vue")['default']
export const LazyUContainer: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Container.vue")['default']
export const LazyUDivider: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Divider.vue")['default']
export const LazyUSkeleton: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/layout/Skeleton.vue")['default']
export const LazyUBreadcrumb: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/Breadcrumb.vue")['default']
export const LazyUCommandPalette: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/CommandPalette.vue")['default']
export const LazyUCommandPaletteGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/CommandPaletteGroup.vue")['default']
export const LazyUHorizontalNavigation: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/HorizontalNavigation.vue")['default']
export const LazyUPagination: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/Pagination.vue")['default']
export const LazyUTabs: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/Tabs.vue")['default']
export const LazyUVerticalNavigation: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/navigation/VerticalNavigation.vue")['default']
export const LazyUContextMenu: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/ContextMenu.vue")['default']
export const LazyUModal: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Modal.vue")['default']
export const LazyUModals: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Modals.client.vue")['default']
export const LazyUNotification: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Notification.vue")['default']
export const LazyUNotifications: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Notifications.vue")['default']
export const LazyUPopover: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Popover.vue")['default']
export const LazyUSlideover: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Slideover.vue")['default']
export const LazyUSlideovers: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Slideovers.client.vue")['default']
export const LazyUTooltip: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/overlays/Tooltip.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyIcon: typeof import("../node_modules/@nuxt/icon/dist/runtime/components/index")['default']
export const LazyColorScheme: typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
export const LazyAccordion: typeof import("../components/ui/accordion/index")['Accordion']
export const LazyAccordionContent: typeof import("../components/ui/accordion/index")['AccordionContent']
export const LazyAccordionItem: typeof import("../components/ui/accordion/index")['AccordionItem']
export const LazyAccordionTrigger: typeof import("../components/ui/accordion/index")['AccordionTrigger']
export const LazyBadge: typeof import("../components/ui/badge/index")['Badge']
export const LazyBreadcrumb: typeof import("../components/ui/breadcrumb/index")['Breadcrumb']
export const LazyBreadcrumbEllipsis: typeof import("../components/ui/breadcrumb/index")['BreadcrumbEllipsis']
export const LazyBreadcrumbItem: typeof import("../components/ui/breadcrumb/index")['BreadcrumbItem']
export const LazyBreadcrumbLink: typeof import("../components/ui/breadcrumb/index")['BreadcrumbLink']
export const LazyBreadcrumbList: typeof import("../components/ui/breadcrumb/index")['BreadcrumbList']
export const LazyBreadcrumbPage: typeof import("../components/ui/breadcrumb/index")['BreadcrumbPage']
export const LazyBreadcrumbSeparator: typeof import("../components/ui/breadcrumb/index")['BreadcrumbSeparator']
export const LazyButton: typeof import("../components/ui/button/index")['Button']
export const LazyCard: typeof import("../components/ui/card/index")['Card']
export const LazyCardHeader: typeof import("../components/ui/card/index")['CardHeader']
export const LazyCardTitle: typeof import("../components/ui/card/index")['CardTitle']
export const LazyCardDescription: typeof import("../components/ui/card/index")['CardDescription']
export const LazyCardContent: typeof import("../components/ui/card/index")['CardContent']
export const LazyCardFooter: typeof import("../components/ui/card/index")['CardFooter']
export const LazyChartTooltip: typeof import("../components/ui/chart/index")['ChartTooltip']
export const LazyChartSingleTooltip: typeof import("../components/ui/chart/index")['ChartSingleTooltip']
export const LazyChartLegend: typeof import("../components/ui/chart/index")['ChartLegend']
export const LazyChartCrosshair: typeof import("../components/ui/chart/index")['ChartCrosshair']
export const LazyBarChart: typeof import("../components/ui/chart-bar/index")['BarChart']
export const LazyDonutChart: typeof import("../components/ui/chart-donut/index")['DonutChart']
export const LazyCheckbox: typeof import("../components/ui/checkbox/index")['Checkbox']
export const LazyCollapsible: typeof import("../components/ui/collapsible/index")['Collapsible']
export const LazyCollapsibleContent: typeof import("../components/ui/collapsible/index")['CollapsibleContent']
export const LazyCollapsibleTrigger: typeof import("../components/ui/collapsible/index")['CollapsibleTrigger']
export const LazyDialog: typeof import("../components/ui/dialog/index")['Dialog']
export const LazyDialogClose: typeof import("../components/ui/dialog/index")['DialogClose']
export const LazyDialogTrigger: typeof import("../components/ui/dialog/index")['DialogTrigger']
export const LazyDialogHeader: typeof import("../components/ui/dialog/index")['DialogHeader']
export const LazyDialogTitle: typeof import("../components/ui/dialog/index")['DialogTitle']
export const LazyDialogDescription: typeof import("../components/ui/dialog/index")['DialogDescription']
export const LazyDialogContent: typeof import("../components/ui/dialog/index")['DialogContent']
export const LazyDialogScrollContent: typeof import("../components/ui/dialog/index")['DialogScrollContent']
export const LazyDialogFooter: typeof import("../components/ui/dialog/index")['DialogFooter']
export const LazyDrawerPortal: typeof import("../components/ui/drawer/index")['DrawerPortal']
export const LazyDrawerTrigger: typeof import("../components/ui/drawer/index")['DrawerTrigger']
export const LazyDrawerClose: typeof import("../components/ui/drawer/index")['DrawerClose']
export const LazyDrawer: typeof import("../components/ui/drawer/index")['Drawer']
export const LazyDrawerOverlay: typeof import("../components/ui/drawer/index")['DrawerOverlay']
export const LazyDrawerContent: typeof import("../components/ui/drawer/index")['DrawerContent']
export const LazyDrawerHeader: typeof import("../components/ui/drawer/index")['DrawerHeader']
export const LazyDrawerFooter: typeof import("../components/ui/drawer/index")['DrawerFooter']
export const LazyDrawerTitle: typeof import("../components/ui/drawer/index")['DrawerTitle']
export const LazyDrawerDescription: typeof import("../components/ui/drawer/index")['DrawerDescription']
export const LazyDropdownMenuPortal: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuPortal']
export const LazyDropdownMenu: typeof import("../components/ui/dropdown-menu/index")['DropdownMenu']
export const LazyDropdownMenuTrigger: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuTrigger']
export const LazyDropdownMenuContent: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuContent']
export const LazyDropdownMenuGroup: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuGroup']
export const LazyDropdownMenuRadioGroup: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioGroup']
export const LazyDropdownMenuItem: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuItem']
export const LazyDropdownMenuCheckboxItem: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuCheckboxItem']
export const LazyDropdownMenuRadioItem: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuRadioItem']
export const LazyDropdownMenuShortcut: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuShortcut']
export const LazyDropdownMenuSeparator: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSeparator']
export const LazyDropdownMenuLabel: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuLabel']
export const LazyDropdownMenuSub: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSub']
export const LazyDropdownMenuSubTrigger: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubTrigger']
export const LazyDropdownMenuSubContent: typeof import("../components/ui/dropdown-menu/index")['DropdownMenuSubContent']
export const LazyInput: typeof import("../components/ui/input/index")['Input']
export const LazyLabel: typeof import("../components/ui/label/index")['Label']
export const LazyPagination: typeof import("../components/ui/pagination/index")['Pagination']
export const LazyPaginationList: typeof import("../components/ui/pagination/index")['PaginationList']
export const LazyPaginationListItem: typeof import("../components/ui/pagination/index")['PaginationListItem']
export const LazyPaginationEllipsis: typeof import("../components/ui/pagination/index")['PaginationEllipsis']
export const LazyPaginationFirst: typeof import("../components/ui/pagination/index")['PaginationFirst']
export const LazyPaginationLast: typeof import("../components/ui/pagination/index")['PaginationLast']
export const LazyPaginationNext: typeof import("../components/ui/pagination/index")['PaginationNext']
export const LazyPaginationPrev: typeof import("../components/ui/pagination/index")['PaginationPrev']
export const LazyProgress: typeof import("../components/ui/progress/index")['Progress']
export const LazyScrollArea: typeof import("../components/ui/scroll-area/index")['ScrollArea']
export const LazyScrollBar: typeof import("../components/ui/scroll-area/index")['ScrollBar']
export const LazySelect: typeof import("../components/ui/select/index")['Select']
export const LazySelectValue: typeof import("../components/ui/select/index")['SelectValue']
export const LazySelectTrigger: typeof import("../components/ui/select/index")['SelectTrigger']
export const LazySelectContent: typeof import("../components/ui/select/index")['SelectContent']
export const LazySelectGroup: typeof import("../components/ui/select/index")['SelectGroup']
export const LazySelectItem: typeof import("../components/ui/select/index")['SelectItem']
export const LazySelectItemText: typeof import("../components/ui/select/index")['SelectItemText']
export const LazySelectLabel: typeof import("../components/ui/select/index")['SelectLabel']
export const LazySelectSeparator: typeof import("../components/ui/select/index")['SelectSeparator']
export const LazySelectScrollUpButton: typeof import("../components/ui/select/index")['SelectScrollUpButton']
export const LazySelectScrollDownButton: typeof import("../components/ui/select/index")['SelectScrollDownButton']
export const LazySeparator: typeof import("../components/ui/separator/index")['Separator']
export const LazySheet: typeof import("../components/ui/sheet/index")['Sheet']
export const LazySheetClose: typeof import("../components/ui/sheet/index")['SheetClose']
export const LazySheetContent: typeof import("../components/ui/sheet/index")['SheetContent']
export const LazySheetDescription: typeof import("../components/ui/sheet/index")['SheetDescription']
export const LazySheetFooter: typeof import("../components/ui/sheet/index")['SheetFooter']
export const LazySheetHeader: typeof import("../components/ui/sheet/index")['SheetHeader']
export const LazySheetTitle: typeof import("../components/ui/sheet/index")['SheetTitle']
export const LazySheetTrigger: typeof import("../components/ui/sheet/index")['SheetTrigger']
export const LazySidebar: typeof import("../components/ui/sidebar/index")['Sidebar']
export const LazySidebarContent: typeof import("../components/ui/sidebar/index")['SidebarContent']
export const LazySidebarFooter: typeof import("../components/ui/sidebar/index")['SidebarFooter']
export const LazySidebarGroup: typeof import("../components/ui/sidebar/index")['SidebarGroup']
export const LazySidebarGroupAction: typeof import("../components/ui/sidebar/index")['SidebarGroupAction']
export const LazySidebarGroupContent: typeof import("../components/ui/sidebar/index")['SidebarGroupContent']
export const LazySidebarGroupLabel: typeof import("../components/ui/sidebar/index")['SidebarGroupLabel']
export const LazySidebarHeader: typeof import("../components/ui/sidebar/index")['SidebarHeader']
export const LazySidebarInput: typeof import("../components/ui/sidebar/index")['SidebarInput']
export const LazySidebarInset: typeof import("../components/ui/sidebar/index")['SidebarInset']
export const LazySidebarMenuAction: typeof import("../components/ui/sidebar/index")['SidebarMenuAction']
export const LazySidebarMenuBadge: typeof import("../components/ui/sidebar/index")['SidebarMenuBadge']
export const LazySidebarMenuButton: typeof import("../components/ui/sidebar/index")['SidebarMenuButton']
export const LazySidebarMenuItem: typeof import("../components/ui/sidebar/index")['SidebarMenuItem']
export const LazySidebarMenuSkeleton: typeof import("../components/ui/sidebar/index")['SidebarMenuSkeleton']
export const LazySidebarMenuSub: typeof import("../components/ui/sidebar/index")['SidebarMenuSub']
export const LazySidebarMenuSubButton: typeof import("../components/ui/sidebar/index")['SidebarMenuSubButton']
export const LazySidebarMenuSubItem: typeof import("../components/ui/sidebar/index")['SidebarMenuSubItem']
export const LazySidebarProvider: typeof import("../components/ui/sidebar/index")['SidebarProvider']
export const LazySidebarRail: typeof import("../components/ui/sidebar/index")['SidebarRail']
export const LazySidebarSeparator: typeof import("../components/ui/sidebar/index")['SidebarSeparator']
export const LazySidebarTrigger: typeof import("../components/ui/sidebar/index")['SidebarTrigger']
export const LazySkeleton: typeof import("../components/ui/skeleton/index")['Skeleton']
export const LazySwitch: typeof import("../components/ui/switch/index")['Switch']
export const LazyTable: typeof import("../components/ui/table/index")['Table']
export const LazyTableBody: typeof import("../components/ui/table/index")['TableBody']
export const LazyTableCell: typeof import("../components/ui/table/index")['TableCell']
export const LazyTableHead: typeof import("../components/ui/table/index")['TableHead']
export const LazyTableHeader: typeof import("../components/ui/table/index")['TableHeader']
export const LazyTableFooter: typeof import("../components/ui/table/index")['TableFooter']
export const LazyTableRow: typeof import("../components/ui/table/index")['TableRow']
export const LazyTableCaption: typeof import("../components/ui/table/index")['TableCaption']
export const LazyTableEmpty: typeof import("../components/ui/table/index")['TableEmpty']
export const LazyTabs: typeof import("../components/ui/tabs/index")['Tabs']
export const LazyTabsTrigger: typeof import("../components/ui/tabs/index")['TabsTrigger']
export const LazyTabsList: typeof import("../components/ui/tabs/index")['TabsList']
export const LazyTabsContent: typeof import("../components/ui/tabs/index")['TabsContent']
export const LazyTooltip: typeof import("../components/ui/tooltip/index")['Tooltip']
export const LazyTooltipContent: typeof import("../components/ui/tooltip/index")['TooltipContent']
export const LazyTooltipProvider: typeof import("../components/ui/tooltip/index")['TooltipProvider']
export const LazyTooltipTrigger: typeof import("../components/ui/tooltip/index")['TooltipTrigger']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyUModals: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyUSlideovers: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
